### ISSUE TITLE
Feature discussion: Profiles

### ISSUE THREAD

**Issue by cH40z-Lord** [Becklyn/BecklynDatabaseDumpBundle#6]
In some cases it might be quite useful for users to create profiles. A profile could contain the following configuration options:

- Backup path
- Connections which should be backed up

When dealing with a larger amount of connections in an app it might drastically enhance the user experience when you could configure such profiles and then just call the dump command with the profile name.
This might also help you when you have different databases that needs to be backed up under different circumstances. Like a few databases needs to be backed up every time you deploy a new version of the app, others when a certain cronjob runs etc.

Given the following configuration example:

```yaml
becklyn_database_dump:
    profiles:
        ci:
            connections:
                - default
                - customers
            directory: /foo/bar
        nightly:
            connections:
                - default
                - customers
                - important_data
                - something_else
```
One could simply call...

```bash
$ symfony becklyn:db:dump --profile=ci
$ symfony becklyn:db:dump --profile=nightly
```
instead of:

```bash
$ symfony becklyn:db:dump --connections=default,customers --path=/foo/bar
$ symfony becklyn:db:dump --connections=default,customers,important_data,something_else
```

When looking at #1 and #2 this might reduce the amount of parameters/configuration one has to do even more.

Feedback? Ideas? Comments?

**Comment by apfelbox** [comment]
I like the idea. This could make the configuration more consistent.

What should we do if we have no connection given? I would propose to run for all configurations.

One other thing: maybe we should use array arguments instead of our custom CSV list? http://symfony.com/doc/current/components/console/introduction.html#using-command-arguments

**Comment by cH40z-Lord** [comment]
> What should we do if we have no connection given? I would propose to run for all configurations.

Right now it falls back to the connections that have been configured via

```yaml
becklyn_database_dump:
    connections:
        # ...
```

That's the default behaviour if you call `sf becklyn:db:dump` without any parameters. Doing something else here might confuse users and is not what I, as a user, would expect.
